version: '3'
services:
  relay:
    build: .
    volumes:
      - ./data:/mnt/
    ports:
      - 8080:8080
    environment:
      - ADDR=0.0.0.0
      - HOSTNAME=relay.04.si
      - HTTPS=true
      - DEBUG=false
      - VALIDATE_SIGNATURES=true
      - PRETTY_LOG=false
      - PUBLISH_BLOCKS=true
      - SLED_PATH=/mnt/sled/db-0.34
      - RUST_LOG=warn
    restart: always
